app_vote:
    resource: "@AppBundle/Controller/VoteController.php"
    type:     annotation

default:
    resource: "@AppBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation