# Sonata Media
#admin_area:
#    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
#    prefix: /admin

#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

default:
    resource: "@AppBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

