services:
    lorempixel.helper:
        class: AppBundle\Service\Helper\LoremPixelHelper
        arguments: []

    lorempixel.wrapper:
        class: AppBundle\Service\Wrapper\LoremPixelWrapper
        arguments: ['@lorempixel.helper']

